global:
  resolve_timeout: 5m

route:
  group_by: [ 'alertname', 'service' ]
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1m
  receiver: 'console'

receivers:
  - name: 'console'
    webhook_configs:
      - url: 'http://localhost:9094/'