receivers:
  otlp:
    protocols:
      grpc: # grpc 默认监听 4317 端口
      http:

processors:
  batch:
  memory_limiter:
    limit_mib: 200
    spike_limit_mib: 50
    check_interval: 5s

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  debug:

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ debug ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ prometheus ]
