name: meilisearch

services:
  meilisearch:
    image: getmeili/meilisearch:v1.11.3
    ports:
      - "7700:7700"
    volumes:
      - /Users/hayson/deployData/meilisearch:/meili_data
    environment:
      MEILI_MASTER_KEY: 12345678
      MEILI_MAX_INDEXING_MEMORY: '1Gb' # 索引最大使用raw量
      MEILI_MAX_INDEXING_THREADS: 4 # 最大线程数
