name: minio

services:
  minio:
    image: bitnami/minio:latest
    environment:
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "12345678"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /Users/hayson/deployData/minio:/bitnami/minio/data