name: nats

services:
  nats:
    image: bitnami/nats:latest
    environment:
      NATS_ENABLE_AUTH: "yes"
      NATS_USERNAME: "nats"
      NATS_PASSWORD: "12345678"
      NATS_EXTRA_ARGS: "-js"
    ports:
      - '4222:4222'
      - '6222:6222'
      - '8222:8222'
    volumes:
      - /Users/hayson/deployData/nats:/bitnami/nats/data
