name: nats

services:
  nats:
    image: nats:latest
    command: "-js -sd /data"
    ports:
      - '4222:4222'
      - '6222:6222'
      - '8222:8222'
    volumes:
      - /Users/hayson/deployData/nats:/data
