name: redis

services:
  redis:
    image: redis/redis-stack:latest
    environment:
      REDIS_ARGS: "--requirepass 12345678"
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - /Users/hayson/deployData/redis:/data