name: tidb

services:
  pd0:
    image: pingcap/pd:latest
    ports:
      - "2379"
    volumes:
      - ./conf/pd.toml:/pd.toml:ro
      - ./data:/data
      - ./logs:/logs
    command:
      - --name=pd0
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd0:2379
      - --advertise-peer-urls=http://pd0:2380
      - --initial-cluster=pd0=http://pd0:2380
      - --data-dir=/data/pd0
      - --config=/pd.toml
    restart: on-failure

  tikv0:
    image: pingcap/tikv:latest
    volumes:
      - ./conf/tikv.toml:/tikv.toml:ro
      - ./data:/data
      - ./logs:/logs
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv0:20160
      - --data-dir=/data/tikv0
      - --pd=pd0:2379
      - --config=/tikv.toml
    depends_on:
      - "pd0"
    restart: on-failure

  tidb:
    image: pingcap/tidb:latest
    ports:
      - "4000:4000"
      - "10080:10080"
    volumes:
      - ./conf/tidb.toml:/tidb.toml:ro
      - ./logs:/logs
    command:
      - --store=tikv
      - --path=pd0:2379
      - --config=/tidb.toml
      - --advertise-address=tidb
    depends_on:
      - "tikv0"
    restart: on-failure

  # monitors
  pushgateway:
    image: prom/pushgateway:latest
    command:
      - --log.level=error
    restart: on-failure
  prometheus:
    user: root
    image: prom/prometheus:latest
    command:
      - --log.level=error
      - --storage.tsdb.path=/data/prometheus
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    volumes:
      - ./conf/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - ./conf/pd.rules.yaml:/etc/prometheus/pd.rules.yaml:ro
      - ./conf/tikv.rules.yaml:/etc/prometheus/tikv.rules.yaml:ro
      - ./conf/tidb.rules.yaml:/etc/prometheus/tidb.rules.yaml:ro
      - ./data:/data
    restart: on-failure
  grafana:
    image: grafana/grafana:latest
    user: "0"
    environment:
      GF_LOG_LEVEL: error
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      GF_PATHS_CONFIG: /etc/grafana/grafana.ini
    volumes:
      - ./conf/grafana:/etc/grafana
      - ./conf/dashboards:/tmp/dashboards
      - ./data/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: on-failure