# pd leader 租约超时时间，单位秒，超时将重新触发选举
lease = 3

[log]
# 日志级别: debug, info, warn, error, fatal.
level = "error"

[log.file]
filename = ""

[metric]
# 向普罗米修斯推送监控指标的时间间隔
interval = "15s"

# 普罗米修斯网关地址
address = "pushgateway:9091"

[schedule]
# region大小超出此值时不会再和其他region合并，单位MiB
max-merge-region-size = 54

# region包含的key数量超出此值时不会再和其他region合并
max-merge-region-keys = 540000

# pd认为tikv已经离线的时间，超出此时间没有心跳，则认为tikv下线，会在其他tikv上补充数据副本
max-store-down-time = "30m"

# 同时进行中的调度region的数量
region-schedule-limit = 2048

# 热点region调度数量
hot-region-schedule-limit = 4

# tikv空间不足的阈值，空间占用超过该阈值时，pd会尽量不再向此节点写入数据
low-space-ratio = 0.8

[replication]
# 数据副本总数，3即为1个leader及2个follower
max-replicas = 3