[log]
# 日志级别: debug, info, warn, error, fatal.
level = "error"

[log.file]
# 日志文件名，当文件名为空时，日志将输出至stderr
filename = ""

[performance]
# cpu使用数量，为0即不限制
max-procs = 0

# 内存使用上限，单位字节，为0即不限制
server-memory-quota = 0

# 单个事务持续的最长时间，单位毫秒
max-txn-ttl = 3600000

# 单个事务包含的最大语句数量
stmt-count-limit = 5000

