# 慢查询日志阈值2s，不指定日志文件时，慢查询日志将输出至stderr
slow-log-threshold = "2s"

# 日志级别: trace, debug, info, warn, error, off.
[log]
level = "error"

[log.file]
# 日志文件名，当文件名为空时，日志将输出至stderr
filename = ""

[storage.block-cache]
# tikv底层使用的内存缓存池大小
capacity = "1GiB"

# 存储及计算使用统一的线程池
[readpool.storage]
use-unified-pool = "true"

[readpool.coprocessor]
use-unified-pool = "true"

