name: nats

services:
  nats:
    image: nats:latest
    command: "-c /nats.conf"
    ports:
      - '4222:4222'
      - '6222:6222'
      - '8222:8222'
    volumes:
      - ./conf/nats.conf:/nats.conf
      - ./data:/data