name: minio

services:
  minio:
    image: minio/minio:latest
    environment:
      MINIO_CONFIG_ENV_FILE: /etc/config.env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./conf/config.env:/etc/config.env
      - ./data:/data/minio
    command:
      - server
      - /data/minio
      - --console-address
      - ":9001"
    restart: on-failure