name: prometheus

services:
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./conf/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./conf/alter_rule.yaml:/etc/prometheus/alter_rule.yaml
    networks:
      - prom-net

  alertmanager:
    image: prom/alertmanager
    ports:
      - '9093:9093'
    volumes:
      - ./conf/alertmanager.yaml:/etc/alertmanager/alertmanager.yml
    networks:
      - prom-net


networks:
  prom-net:
    driver: bridge