name: nebula-graph

services:
  metad:
    image: vesoft/nebula-metad:latest
    environment:
      USER: root
    command:
      - --meta_server_addrs=metad:9559 # 全部meta服务的地址列表
      - --local_ip=metad
      - --ws_ip=metad # http服务的ip地址
      - --port=9559
      - --ws_http_port=19559 # http服务的端口
      - --data_path=/data/meta
      - --logtostderr=true
      - --redirect_stdout=false
      - --v=0
      - --minloglevel=0 # 日志级别，0为info
      - --timezone_name=UTC+08:00
    healthcheck:
      test: [ "CMD", "curl", "-sf", "http://metad:19559/status" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - "9559"
      - "19559"
      - "19560"
    volumes:
      - ./data/meta:/data/meta
    networks:
      - nebula-net
    restart: on-failure
    cap_add:
      - SYS_PTRACE

  # 需要执行 ADD HOSTS "storaged":9779;
  storaged:
    image: vesoft/nebula-storaged:latest
    environment:
      USER: root
    command:
      - --meta_server_addrs=metad:9559
      - --local_ip=storaged
      - --ws_ip=storaged
      - --port=9779
      - --ws_http_port=19779
      - --data_path=/data/storage
      - --logtostderr=true
      - --redirect_stdout=false
      - --v=0
      - --minloglevel=0
      - --timezone_name=UTC+08:00
      - --rocksdb_block_cache=128 # rocksdb块缓存大小，128M
      - --max_edge_returned_per_vertex=10000 # 每个节点最多遍历多少临边，避免稠密点耗费性能
    depends_on:
      - metad
    healthcheck:
      test: [ "CMD", "curl", "-sf", "http://storaged:19779/status" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - "9779"
      - "19779"
      - "19780"
    volumes:
      - ./data/storage:/data/storage
    networks:
      - nebula-net
    restart: on-failure
    cap_add:
      - SYS_PTRACE

  graphd:
    image: vesoft/nebula-graphd:latest
    environment:
      USER: root
    command:
      - --meta_server_addrs=metad:9559
      - --port=9669
      - --local_ip=graphd
      - --ws_ip=graphd
      - --ws_http_port=19669
      - --logtostderr=true
      - --redirect_stdout=false
      - --v=0
      - --minloglevel=0
      - --timezone_name=UTC+08:00
    depends_on:
      - storaged
    healthcheck:
      test: [ "CMD", "curl", "-sf", "http://graphd:19669/status" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - "9669:9669"
      - "19669"
      - "19670"
    networks:
      - nebula-net
    restart: on-failure
    cap_add:
      - SYS_PTRACE

  web:
    image: vesoft/nebula-graph-studio:latest
    environment:
      USER: root
    ports:
      - "7001:7001"
    networks:
      - nebula-net

networks:
  nebula-net: